name = "ls"
command = "/home/luke/supervisord/ls"
directory = "/home/luke/supervisord"
autostart = true
autorestart = true
stdout_logfile = "/home/luke/supervisord/ls.log"
stderr_logfile = "/home/luke/supervisord/ls.err"a