name = "my_app"
command = "echo 'Replace this with your process command!'"
directory = "/home/luke/supervisord"
autostart = true
autorestart = true
stdout_logfile = "/home/luke/supervisord/my_app.log"
stderr_logfile = "/home/luke/supervisord/my_app.err"
