[program]
name = "my_app"
command = "echo 'Replace this with your process command!'"
directory = "/home/luke/supervisorr"
autostart = true
autorestart = true
stdout_logfile = "/home/luke/supervisorr/my_app.log"
stderr_logfile = "/home/luke/supervisorr/my_app.err"
